package engine

// Generated by OdinGlue.roc from the platform's `requires` block.
// Do not edit by hand; regenerate instead:
//   roc glue ./OdinGlue.roc <out-dir> <platform>/main.roc

// Every offset below is the 64-bit layout. This spec emits one pointer
// width, so the host must be a 64-bit target.
#assert(size_of(uintptr) == 8)

Roc_List :: struct($T: typeid) {
	elements:              [^]T,
	length:                uint,
	capacity_or_alloc_ptr: uint,
}

#assert(size_of(Roc_List(u8)) == 24)
#assert(align_of(Roc_List(u8)) == 8)

Roc_Init :: struct {
	frame: u64,
	bodies: Roc_List(Roc_Init_Bodies),
}

#assert(size_of(Roc_Init) == 32)
#assert(align_of(Roc_Init) == 8)
#assert(offset_of(Roc_Init, frame) == 0)
#assert(size_of(type_of(Roc_Init{}.frame)) == 8)
#assert(offset_of(Roc_Init, bodies) == 8)
#assert(size_of(type_of(Roc_Init{}.bodies)) == 24)

Roc_Init_Bodies :: struct {
	mass: f64,
	v: f32,
	x: f32,
	x_prev: f32,
}

#assert(size_of(Roc_Init_Bodies) == 24)
#assert(align_of(Roc_Init_Bodies) == 8)
#assert(offset_of(Roc_Init_Bodies, mass) == 0)
#assert(size_of(type_of(Roc_Init_Bodies{}.mass)) == 8)
#assert(offset_of(Roc_Init_Bodies, v) == 8)
#assert(size_of(type_of(Roc_Init_Bodies{}.v)) == 4)
#assert(offset_of(Roc_Init_Bodies, x) == 12)
#assert(size_of(type_of(Roc_Init_Bodies{}.x)) == 4)
#assert(offset_of(Roc_Init_Bodies, x_prev) == 16)
#assert(size_of(type_of(Roc_Init_Bodies{}.x_prev)) == 4)

Roc_Step_Arg0 :: Roc_Init
Roc_Step_Arg0_Bodies :: Roc_Init_Bodies
Roc_Step :: Roc_Init
Roc_Step_Bodies :: Roc_Init_Bodies

// The Roc app defines these symbols at the final link.
@(default_calling_convention = "c")
foreign {
	roc_init :: proc(arg0: u64) -> Roc_Init ---
	roc_step :: proc(arg0: Roc_Init, arg1: f32) -> Roc_Init ---
}
