package engine

// Generated by OdinGlue.roc from the platform's `requires` block.
// Do not edit by hand; regenerate instead:
//   roc glue ./OdinGlue.roc <out-dir> <platform>/main.roc

// Every offset below is the 64-bit layout. This spec emits one pointer
// width, so the host must be a 64-bit target.
#assert(size_of(uintptr) == 8)

// The helpers below allocate and free through roc_alloc and roc_dealloc.
// The host defines both in this package, because the Roc app calls them.
//
// A refcounted allocation keeps a header in front of its data. The
// refcount is the int just before the data, and 0 marks static data,
// which is never freed. A list whose elements hold refcounted values also
// keeps its element count in the int before the refcount.

@(private = "file")
roc_refcount :: proc(data: rawptr) -> ^int {
	return (^int)(uintptr(data) - size_of(int))
}

@(private = "file")
roc_header :: proc(elem_align: uint, elements_refcounted: bool) -> (header, alignment: uint) {
	header = max(2 * size_of(uint) if elements_refcounted else size_of(uint), elem_align)
	alignment = max(size_of(uint), elem_align)
	return
}

// Returns the data pointer of a new allocation with refcount 1.
@(private = "file")
roc_alloc_refcounted :: proc(data_bytes, elem_align: uint, elements_refcounted: bool, count: uint) -> rawptr {
	header, alignment := roc_header(elem_align, elements_refcounted)
	base := roc_alloc(header + data_bytes, alignment)
	if base == nil {
		panic("roc_alloc returned nil")
	}
	data := rawptr(uintptr(base) + uintptr(header))
	roc_refcount(data)^ = 1
	if elements_refcounted {
		(^uint)(uintptr(data) - 2 * size_of(uint))^ = count
	}
	return data
}

// Returns true when this call dropped the last reference.
@(private = "file")
roc_release :: proc(data: rawptr) -> bool {
	if data == nil {
		return false
	}
	rc := roc_refcount(data)
	if rc^ == 0 {
		return false
	}
	rc^ -= 1
	return rc^ == 0
}

@(private = "file")
roc_free :: proc(data: rawptr, elem_align: uint, elements_refcounted: bool) {
	header, alignment := roc_header(elem_align, elements_refcounted)
	roc_dealloc(rawptr(uintptr(data) - uintptr(header)), alignment)
}

Roc_List :: struct($T: typeid) {
	elements:              [^]T,
	length:                uint,
	capacity_or_alloc_ptr: uint,
}

#assert(size_of(Roc_List(u8)) == 24)
#assert(align_of(Roc_List(u8)) == 8)

// A seamless slice tags the low bit of capacity_or_alloc_ptr and keeps
// the data pointer of the allocation it shares there.
@(private = "file")
roc_list_data :: proc(list: Roc_List($T)) -> rawptr {
	if list.capacity_or_alloc_ptr & 1 != 0 {
		return rawptr(uintptr(list.capacity_or_alloc_ptr &~ 1))
	}
	return list.elements
}

// The list takes over the references the elements hold. An empty slice
// allocates nothing.
@(private = "file")
roc_list_from_slice_with :: proc(elems: []$T, elements_refcounted: bool) -> Roc_List(T) {
	if len(elems) == 0 {
		return {}
	}
	n := uint(len(elems))
	data := roc_alloc_refcounted(n * size_of(T), align_of(T), elements_refcounted, n)
	list := Roc_List(T){elements = ([^]T)(data), length = n, capacity_or_alloc_ptr = n << 1}
	copy(list.elements[:n], elems)
	return list
}

@(private = "file")
roc_list_decref_flat :: proc(list: Roc_List($T)) {
	data := roc_list_data(list)
	if roc_release(data) {
		roc_free(data, align_of(T), false)
	}
}

// Releases the elements only when this call dropped the last reference.
@(private = "file")
roc_list_decref_elements :: proc(list: Roc_List($T), release: proc(value: T)) {
	data := roc_list_data(list)
	if !roc_release(data) {
		return
	}
	count := list.length
	if list.capacity_or_alloc_ptr & 1 != 0 {
		count = (^uint)(uintptr(data) - 2 * size_of(uint))^
	}
	for elem in ([^]T)(data)[:count] {
		release(elem)
	}
	roc_free(data, align_of(T), true)
}

Roc_Init :: struct {
	frame: u64,
	bodies: Roc_List(Roc_Init_Bodies),
}

#assert(size_of(Roc_Init) == 32)
#assert(align_of(Roc_Init) == 8)
#assert(offset_of(Roc_Init, frame) == 0)
#assert(size_of(type_of(Roc_Init{}.frame)) == 8)
#assert(offset_of(Roc_Init, bodies) == 8)
#assert(size_of(type_of(Roc_Init{}.bodies)) == 24)

Roc_Init_Bodies :: struct {
	mass: f64,
	v: f32,
	x: f32,
	x_prev: f32,
}

#assert(size_of(Roc_Init_Bodies) == 24)
#assert(align_of(Roc_Init_Bodies) == 8)
#assert(offset_of(Roc_Init_Bodies, mass) == 0)
#assert(size_of(type_of(Roc_Init_Bodies{}.mass)) == 8)
#assert(offset_of(Roc_Init_Bodies, v) == 8)
#assert(size_of(type_of(Roc_Init_Bodies{}.v)) == 4)
#assert(offset_of(Roc_Init_Bodies, x) == 12)
#assert(size_of(type_of(Roc_Init_Bodies{}.x)) == 4)
#assert(offset_of(Roc_Init_Bodies, x_prev) == 16)
#assert(size_of(type_of(Roc_Init_Bodies{}.x_prev)) == 4)

Roc_Step_Arg0 :: Roc_Init
Roc_Step_Arg0_Bodies :: Roc_Init_Bodies
Roc_Step :: Roc_Init
Roc_Step_Bodies :: Roc_Init_Bodies

roc_init_decref :: proc(value: Roc_Init) {
	roc_list_decref_roc_init_bodies(value.bodies)
}

roc_list_decref_roc_init_bodies :: proc(list: Roc_List(Roc_Init_Bodies)) {
	roc_list_decref_flat(list)
}

roc_list_from_slice_roc_init_bodies :: proc(elems: []Roc_Init_Bodies) -> Roc_List(Roc_Init_Bodies) {
	return roc_list_from_slice_with(elems, false)
}

roc_decref :: proc {
	roc_init_decref,
}

roc_list_decref :: proc {
	roc_list_decref_roc_init_bodies,
}

roc_list_from_slice :: proc {
	roc_list_from_slice_roc_init_bodies,
}

// The Roc app defines these symbols at the final link.
@(default_calling_convention = "c")
foreign {
	roc_init :: proc(arg0: u64) -> Roc_Init ---
	roc_step :: proc(arg0: Roc_Init, arg1: f32) -> Roc_Init ---
}
