package engine

// Generated by OdinGlue.roc from the platform's `requires` block.
// Do not edit by hand; regenerate instead:
//   roc glue ./OdinGlue.roc <out-dir> <platform>/main.roc

// Every offset below is the 64-bit layout. This spec emits one pointer
// width, so the host must be a 64-bit target.
#assert(size_of(uintptr) == 8)

Roc_Str :: struct {
	bytes:    [^]u8,
	length:   uint,
	capacity: uint,
}
#assert(size_of(Roc_Str) == 24)
#assert(align_of(Roc_Str) == 8)

Roc_List :: struct($T: typeid) {
	elements:              [^]T,
	length:                uint,
	capacity_or_alloc_ptr: uint,
}

#assert(size_of(Roc_List(u8)) == 24)
#assert(align_of(Roc_List(u8)) == 8)

Roc_Init_Arg0 :: struct {
	seed: u64,
	meshes: Roc_List(Roc_Init_Arg0_Meshes),
}

#assert(size_of(Roc_Init_Arg0) == 32)
#assert(align_of(Roc_Init_Arg0) == 8)
#assert(offset_of(Roc_Init_Arg0, seed) == 0)
#assert(size_of(type_of(Roc_Init_Arg0{}.seed)) == 8)
#assert(offset_of(Roc_Init_Arg0, meshes) == 8)
#assert(size_of(type_of(Roc_Init_Arg0{}.meshes)) == 24)

Roc_Init_Arg0_Meshes :: struct {
	name: Roc_Str,
	id: u32,
}

#assert(size_of(Roc_Init_Arg0_Meshes) == 32)
#assert(align_of(Roc_Init_Arg0_Meshes) == 8)
#assert(offset_of(Roc_Init_Arg0_Meshes, name) == 0)
#assert(size_of(type_of(Roc_Init_Arg0_Meshes{}.name)) == 24)
#assert(offset_of(Roc_Init_Arg0_Meshes, id) == 24)
#assert(size_of(type_of(Roc_Init_Arg0_Meshes{}.id)) == 4)

Roc_Step_Arg1 :: struct {
	held: Roc_List(u16),
	pressed: Roc_List(u16),
	mouse: Roc_Step_Arg1_Mouse,
}

#assert(size_of(Roc_Step_Arg1) == 56)
#assert(align_of(Roc_Step_Arg1) == 8)
#assert(offset_of(Roc_Step_Arg1, held) == 0)
#assert(size_of(type_of(Roc_Step_Arg1{}.held)) == 24)
#assert(offset_of(Roc_Step_Arg1, pressed) == 24)
#assert(size_of(type_of(Roc_Step_Arg1{}.pressed)) == 24)
#assert(offset_of(Roc_Step_Arg1, mouse) == 48)
#assert(size_of(type_of(Roc_Step_Arg1{}.mouse)) == 8)

Roc_Step_Arg1_Mouse :: struct {
	dx: f32,
	dy: f32,
}

#assert(size_of(Roc_Step_Arg1_Mouse) == 8)
#assert(align_of(Roc_Step_Arg1_Mouse) == 4)
#assert(offset_of(Roc_Step_Arg1_Mouse, dx) == 0)
#assert(size_of(type_of(Roc_Step_Arg1_Mouse{}.dx)) == 4)
#assert(offset_of(Roc_Step_Arg1_Mouse, dy) == 4)
#assert(size_of(type_of(Roc_Step_Arg1_Mouse{}.dy)) == 4)

Roc_View :: struct {
	draws: Roc_List(Roc_View_Draws),
	camera: Roc_View_Camera,
}

#assert(size_of(Roc_View) == 56)
#assert(align_of(Roc_View) == 8)
#assert(offset_of(Roc_View, draws) == 0)
#assert(size_of(type_of(Roc_View{}.draws)) == 24)
#assert(offset_of(Roc_View, camera) == 24)
#assert(size_of(type_of(Roc_View{}.camera)) == 28)

Roc_View_Draws :: struct {
	id: u64,
	mesh: u32,
	pos: Roc_View_Draws_Pos,
	scale: Roc_View_Draws_Pos,
	tint: Roc_View_Draws_Tint,
	yaw: f32,
}

#assert(size_of(Roc_View_Draws) == 56)
#assert(align_of(Roc_View_Draws) == 8)
#assert(offset_of(Roc_View_Draws, id) == 0)
#assert(size_of(type_of(Roc_View_Draws{}.id)) == 8)
#assert(offset_of(Roc_View_Draws, mesh) == 8)
#assert(size_of(type_of(Roc_View_Draws{}.mesh)) == 4)
#assert(offset_of(Roc_View_Draws, pos) == 12)
#assert(size_of(type_of(Roc_View_Draws{}.pos)) == 12)
#assert(offset_of(Roc_View_Draws, scale) == 24)
#assert(size_of(type_of(Roc_View_Draws{}.scale)) == 12)
#assert(offset_of(Roc_View_Draws, tint) == 36)
#assert(size_of(type_of(Roc_View_Draws{}.tint)) == 12)
#assert(offset_of(Roc_View_Draws, yaw) == 48)
#assert(size_of(type_of(Roc_View_Draws{}.yaw)) == 4)

Roc_View_Draws_Pos :: struct {
	x: f32,
	y: f32,
	z: f32,
}

#assert(size_of(Roc_View_Draws_Pos) == 12)
#assert(align_of(Roc_View_Draws_Pos) == 4)
#assert(offset_of(Roc_View_Draws_Pos, x) == 0)
#assert(size_of(type_of(Roc_View_Draws_Pos{}.x)) == 4)
#assert(offset_of(Roc_View_Draws_Pos, y) == 4)
#assert(size_of(type_of(Roc_View_Draws_Pos{}.y)) == 4)
#assert(offset_of(Roc_View_Draws_Pos, z) == 8)
#assert(size_of(type_of(Roc_View_Draws_Pos{}.z)) == 4)

Roc_View_Draws_Scale :: Roc_View_Draws_Pos
Roc_View_Draws_Tint :: struct {
	b: f32,
	g: f32,
	r: f32,
}

#assert(size_of(Roc_View_Draws_Tint) == 12)
#assert(align_of(Roc_View_Draws_Tint) == 4)
#assert(offset_of(Roc_View_Draws_Tint, b) == 0)
#assert(size_of(type_of(Roc_View_Draws_Tint{}.b)) == 4)
#assert(offset_of(Roc_View_Draws_Tint, g) == 4)
#assert(size_of(type_of(Roc_View_Draws_Tint{}.g)) == 4)
#assert(offset_of(Roc_View_Draws_Tint, r) == 8)
#assert(size_of(type_of(Roc_View_Draws_Tint{}.r)) == 4)

Roc_View_Camera :: struct {
	eye: Roc_View_Draws_Pos,
	fov_y: f32,
	target: Roc_View_Draws_Pos,
}

#assert(size_of(Roc_View_Camera) == 28)
#assert(align_of(Roc_View_Camera) == 4)
#assert(offset_of(Roc_View_Camera, eye) == 0)
#assert(size_of(type_of(Roc_View_Camera{}.eye)) == 12)
#assert(offset_of(Roc_View_Camera, fov_y) == 12)
#assert(size_of(type_of(Roc_View_Camera{}.fov_y)) == 4)
#assert(offset_of(Roc_View_Camera, target) == 16)
#assert(size_of(type_of(Roc_View_Camera{}.target)) == 12)

Roc_View_Camera_Eye :: Roc_View_Draws_Pos
Roc_View_Camera_Target :: Roc_View_Draws_Pos

// The Roc app defines these symbols at the final link.
@(default_calling_convention = "c")
foreign {
	roc_init :: proc(arg0: Roc_Init_Arg0) -> rawptr ---
	roc_step :: proc(arg0: rawptr, arg1: Roc_Step_Arg1, arg2: f32) -> rawptr ---
	roc_view :: proc(arg0: rawptr) -> Roc_View ---
	roc_drop_model :: proc(arg0: rawptr) -> struct{} ---
}
