# Generated by roc scripts/build.roc -- keys from the Keycode enum in
# sokol-odin/sokol/app/app.odin. Do not edit.
import Vocabulary exposing [Input]

# A named sokol key code. The game decides what a key means.
Key := [
    Space,
    Apostrophe,
    Comma,
    Minus,
    Period,
    Slash,
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    Semicolon,
    Equal,
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    LeftBracket,
    Backslash,
    RightBracket,
    GraveAccent,
    World1,
    World2,
    Escape,
    Enter,
    Tab,
    Backspace,
    Insert,
    Delete,
    Right,
    Left,
    Down,
    Up,
    PageUp,
    PageDown,
    Home,
    End,
    CapsLock,
    ScrollLock,
    NumLock,
    PrintScreen,
    Pause,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,
    F25,
    Kp0,
    Kp1,
    Kp2,
    Kp3,
    Kp4,
    Kp5,
    Kp6,
    Kp7,
    Kp8,
    Kp9,
    KpDecimal,
    KpDivide,
    KpMultiply,
    KpSubtract,
    KpAdd,
    KpEnter,
    KpEqual,
    LeftShift,
    LeftControl,
    LeftAlt,
    LeftSuper,
    RightShift,
    RightControl,
    RightAlt,
    RightSuper,
    Menu,
].{
    code : Key -> U16
    code = |key| match key {
        Space => 32
        Apostrophe => 39
        Comma => 44
        Minus => 45
        Period => 46
        Slash => 47
        Num0 => 48
        Num1 => 49
        Num2 => 50
        Num3 => 51
        Num4 => 52
        Num5 => 53
        Num6 => 54
        Num7 => 55
        Num8 => 56
        Num9 => 57
        Semicolon => 59
        Equal => 61
        A => 65
        B => 66
        C => 67
        D => 68
        E => 69
        F => 70
        G => 71
        H => 72
        I => 73
        J => 74
        K => 75
        L => 76
        M => 77
        N => 78
        O => 79
        P => 80
        Q => 81
        R => 82
        S => 83
        T => 84
        U => 85
        V => 86
        W => 87
        X => 88
        Y => 89
        Z => 90
        LeftBracket => 91
        Backslash => 92
        RightBracket => 93
        GraveAccent => 96
        World1 => 161
        World2 => 162
        Escape => 256
        Enter => 257
        Tab => 258
        Backspace => 259
        Insert => 260
        Delete => 261
        Right => 262
        Left => 263
        Down => 264
        Up => 265
        PageUp => 266
        PageDown => 267
        Home => 268
        End => 269
        CapsLock => 280
        ScrollLock => 281
        NumLock => 282
        PrintScreen => 283
        Pause => 284
        F1 => 290
        F2 => 291
        F3 => 292
        F4 => 293
        F5 => 294
        F6 => 295
        F7 => 296
        F8 => 297
        F9 => 298
        F10 => 299
        F11 => 300
        F12 => 301
        F13 => 302
        F14 => 303
        F15 => 304
        F16 => 305
        F17 => 306
        F18 => 307
        F19 => 308
        F20 => 309
        F21 => 310
        F22 => 311
        F23 => 312
        F24 => 313
        F25 => 314
        Kp0 => 320
        Kp1 => 321
        Kp2 => 322
        Kp3 => 323
        Kp4 => 324
        Kp5 => 325
        Kp6 => 326
        Kp7 => 327
        Kp8 => 328
        Kp9 => 329
        KpDecimal => 330
        KpDivide => 331
        KpMultiply => 332
        KpSubtract => 333
        KpAdd => 334
        KpEnter => 335
        KpEqual => 336
        LeftShift => 340
        LeftControl => 341
        LeftAlt => 342
        LeftSuper => 343
        RightShift => 344
        RightControl => 345
        RightAlt => 346
        RightSuper => 347
        Menu => 348
    }

    held : Input, Key -> Bool
    held = |input, key| List.contains(input.held, code(key))

    pressed : Input, Key -> Bool
    pressed = |input, key| List.contains(input.pressed, code(key))

    # 1.0 when only pos is held, -1.0 when only neg is held, else 0.0.
    axis : Input, Key, Key -> F32
    axis = |input, neg, pos| (if held(input, pos) 1.0 else 0.0) - (if held(input, neg) 1.0 else 0.0)
}

expect Key.code(Space) == 32
expect Key.code(W) == 87
expect Key.code(Num0) == 48
expect Key.code(Kp0) == 320
expect Key.code(Escape) == 256

idle : Input
idle = { held: [], pressed: [], mouse: { dx: 0.0, dy: 0.0 } }

expect Key.held({ ..idle, held: [87] }, W) and !Key.held({ ..idle, pressed: [87] }, W)
expect Key.pressed({ ..idle, pressed: [32] }, Space) and !Key.pressed({ ..idle, held: [32] }, Space)
expect Key.axis({ ..idle, held: [87] }, S, W) == 1.0
expect Key.axis({ ..idle, held: [83] }, S, W) == -1.0
expect Key.axis({ ..idle, held: [83, 87] }, S, W) == 0.0
expect Key.axis(idle, S, W) == 0.0
