Keys := [].{
	sokol_app_path : Str
	sokol_app_path = "sokol-odin/sokol/app/app.odin"

	KeyEntry : { tag : Str, code : U16 }

	# Reads the body of `Keycode :: enum i32 { ... }`, one `NAME = code,` per line.
	# INVALID is 0, which sokol never reports, so it gets no tag.
	parse_keycodes : Str -> Try(List(KeyEntry), [NoKeycodeEnum, BadKeycodeLine(Str)])
	parse_keycodes = |source| {
		body = match Str.split_first(source, "Keycode :: enum i32 {") {
			Ok({ after, .. }) => match Str.split_first(after, "}") {
				Ok({ before, .. }) => before
				Err(_) => return Err(NoKeycodeEnum)
			}
			Err(_) => return Err(NoKeycodeEnum)
		}
		var $entries = []
		for line in Str.split_on(body, "\n").map(Str.trim) {
			match Str.split_first(line, " = ") {
				_ if line == "" => {}
				Ok({ before: "INVALID", .. }) => {}
				Ok({ before, after }) => match U16.from_str(Str.drop_suffix(after, ",")) {
					Ok(code) => {
						$entries = $entries.append({ tag: key_tag(before), code })
					}
					Err(_) => return Err(BadKeycodeLine(line))
				}
				Err(_) => return Err(BadKeycodeLine(line))
			}
		}
		Ok($entries)
	}

	# LEFT_SHIFT becomes LeftShift. A tag cannot start with a digit, so _0 becomes Num0.
	key_tag : Str -> Str
	key_tag = |name|
		if Str.starts_with(name, "_") {
			Str.concat("Num", Str.drop_prefix(name, "_"))
		} else {
			Str.join_with(Str.split_on(name, "_").map(capitalized), "")
		}

	capitalized : Str -> Str
	capitalized = |word| {
		lower = Str.to_utf8(Str.with_ascii_lowercased(word))
		first = Str.to_utf8(word).take_first(1)
		Str.from_utf8(List.concat(first, lower.drop_first(1))) ?? word
	}

	key_module : List(KeyEntry) -> Str
	key_module = |keys| {
		tags = Str.join_with(keys.map(|key| "    ${key.tag},\n"), "")
		codes = Str.join_with(keys.map(|key| "        ${key.tag} => ${key.code.to_str()}\n"), "")
		Str.join_with([key_module_head, key_module_intro, "Key := [\n", tags, "].{\n", key_module_code_head, codes, key_module_tail], "")
	}

	key_module_head : Str
	key_module_head = "# Generated by roc scripts/build.roc -- keys from the Keycode enum in\n# ${sokol_app_path}. Do not edit.\n"

	key_module_intro : Str
	key_module_intro =
		\\import Vocabulary exposing [Input]
		\\
		\\# A named sokol key code. The game decides what a key means.
		\\

	key_module_code_head : Str
	key_module_code_head =
		\\    code : Key -> U16
		\\    code = |key| match key {
		\\

	key_module_tail : Str
	key_module_tail =
		\\    }
		\\
		\\    held : Input, Key -> Bool
		\\    held = |input, key| List.contains(input.held, code(key))
		\\
		\\    pressed : Input, Key -> Bool
		\\    pressed = |input, key| List.contains(input.pressed, code(key))
		\\
		\\    # 1.0 when only pos is held, -1.0 when only neg is held, else 0.0.
		\\    axis : Input, Key, Key -> F32
		\\    axis = |input, neg, pos| (if held(input, pos) 1.0 else 0.0) - (if held(input, neg) 1.0 else 0.0)
		\\}
		\\
		\\expect Key.code(Space) == 32
		\\expect Key.code(W) == 87
		\\expect Key.code(Num0) == 48
		\\expect Key.code(Kp0) == 320
		\\expect Key.code(Escape) == 256
		\\
		\\idle : Input
		\\idle = { held: [], pressed: [], mouse: { dx: 0.0, dy: 0.0 } }
		\\
		\\expect Key.held({ ..idle, held: [87] }, W) and !Key.held({ ..idle, pressed: [87] }, W)
		\\expect Key.pressed({ ..idle, pressed: [32] }, Space) and !Key.pressed({ ..idle, held: [32] }, Space)
		\\expect Key.axis({ ..idle, held: [87] }, S, W) == 1.0
		\\expect Key.axis({ ..idle, held: [83] }, S, W) == -1.0
		\\expect Key.axis({ ..idle, held: [83, 87] }, S, W) == 0.0
		\\expect Key.axis(idle, S, W) == 0.0
		\\
}

expect Keys.key_tag("SPACE") == "Space"
expect Keys.key_tag("LEFT_SHIFT") == "LeftShift"
expect Keys.key_tag("F1") == "F1"
expect Keys.key_tag("WORLD_1") == "World1"
expect Keys.key_tag("_0") == "Num0"
expect Keys.key_tag("KP_0") == "Kp0"
expect Keys.key_tag("KP_DECIMAL") == "KpDecimal"

sokol_keycode_sample : Str
sokol_keycode_sample =
	\\Mouse_Button :: enum i32 {
	\\    LEFT = 0,
	\\}
	\\Keycode :: enum i32 {
	\\    INVALID = 0,
	\\    SPACE = 32,
	\\    _0 = 48,
	\\    LEFT_SHIFT = 340,
	\\}
	\\Touch_Point :: struct {
	\\    changed : bool,
	\\}

expect Keys.parse_keycodes(sokol_keycode_sample) == Ok([{ tag: "Space", code: 32 }, { tag: "Num0", code: 48 }, { tag: "LeftShift", code: 340 }])
expect Keys.parse_keycodes("Mouse_Button :: enum i32 {\n    LEFT = 0,\n}") == Err(NoKeycodeEnum)
expect Keys.parse_keycodes("Keycode :: enum i32 {\n    SPACE = 32,\n    MENU = 1 << 9,\n}") == Err(BadKeycodeLine("MENU = 1 << 9,"))

expect {
	out = Keys.key_module([{ tag: "Space", code: 32 }, { tag: "W", code: 87 }])
	Str.contains(out, "Key := [\n    Space,\n    W,\n].{")
		and Str.contains(out, "        Space => 32\n        W => 87\n")
		and Str.starts_with(out, "# Generated by roc scripts/build.roc -- keys")
}
